apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uw4z2oz41-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uw4z2oz41-java-springboot 
  name: uw4z2oz41-java-springboot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uw4z2oz41-java-springboot 
